[build]
  command="ng build"
  publish="dist/angular-quickstart"
  functions = "netlify/functions/"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[plugins]]
  package = "@netlify/plugin-functions-install-core"

  [plugins.inputs.postBuild]
    enable = true

  [plugins.inputs]
    enable = false